### ISSUE TITLE
Using with the IoT shield

### ISSUE THREAD

**Issue by abhatikar** [sixfab/Sixfab_PPP_Installer#1]
Hi,

I am using the Sixfab RPi CellularIoT App Shield and trying to connect to internet using a vodafone ireland normal sim. I am using this in conjunction with the Rasperry pi 3 running ubuntu mate.
Could you please help what am I missing as i am not getting a remote ip ?

abhatikar@abhatikar-gateway:~$ sudo pon
pppd options in effect:
debug		# (from /etc/ppp/peers/provider)
updetach		# (from /etc/ppp/peers/provider)
dump		# (from /etc/ppp/peers/provider)
noauth		# (from /etc/ppp/peers/provider)
remotename 3gppp		# (from /etc/ppp/peers/provider)
/dev/ttyS0		# (from /etc/ppp/peers/provider)
115200		# (from /etc/ppp/peers/provider)
lock		# (from /etc/ppp/peers/provider)
connect chat -s -v -f /etc/chatscripts/chat-connect -T hs.vodafone.ie		# (from /etc/ppp/peers/provider)
disconnect chat -s -v -f /etc/chatscripts/chat-disconnect		# (from /etc/ppp/peers/provider)
nocrtscts		# (from /etc/ppp/peers/provider)
modem		# (from /etc/ppp/peers/provider)
asyncmap 0		# (from /etc/ppp/options)
lcp-echo-failure 4		# (from /etc/ppp/options)
lcp-echo-interval 30		# (from /etc/ppp/options)
hide-password		# (from /etc/ppp/peers/provider)
novj		# (from /etc/ppp/peers/provider)
novjccomp		# (from /etc/ppp/peers/provider)
ipcp-accept-local		# (from /etc/ppp/peers/provider)
ipcp-accept-remote		# (from /etc/ppp/peers/provider)
ipparam 3gppp		# (from /etc/ppp/peers/provider)
noipdefault		# (from /etc/ppp/peers/provider)
ipcp-max-failure 30		# (from /etc/ppp/peers/provider)
defaultroute		# (from /etc/ppp/peers/provider)
usepeerdns		# (from /etc/ppp/peers/provider)
noccp		# (from /etc/ppp/peers/provider)
noipx		# (from /etc/ppp/options)
abort on (BUSY)
abort on (NO CARRIER)
abort on (NO DIALTONE)
abort on (ERROR)
abort on (NO ANSWER)
timeout set to 30 seconds
send (AT^M)
expect (OK)
^M
OK
 -- got it

send (ATE0^M)
expect (OK)
^M
^M
OK
 -- got it

send (ATI;+CSUB;+CSQ;+COPS?;+CGREG?;&D2^M)
expect (OK)
^M
^M
Quectel^M
BG96^M
Revision: BG96MAR02A07M1G^M
^M
SubEdition: V08^M
^M
+CSQ: 15,0^M
^M
+COPS: 1,0,"vodafone IE vodafone IE",0^M
^M
+CGREG: 0,1^M
^M
OK
 -- got it

send (AT+CGDCONT=1,"IP","hs.vodafone.ie",,0,0^M)
expect (OK)
^M
^M
OK
 -- got it

send (AT+QCFG="nwscanseq",01,1^M)
expect (OK)
^M
^M
OK
 -- got it

send (AT+QCFG="nwscanmode",1,1^M)
expect (OK)
^M
^M
OK
 -- got it

send (AT+QCFG="iotopmode",2,1^M)
expect (OK)
^M
^M
OK
 -- got it

send (ATD*99#^M)
expect (CONNECT)
^M
^M
CONNECT
 -- got it

Script chat -s -v -f /etc/chatscripts/chat-connect -T hs.vodafone.ie finished (pid 1728), status = 0x0
Serial connection established.
using channel 2
Using interface ppp0
Connect: ppp0 <--> /dev/ttyS0
sent [LCP ConfReq id=0x1 <asyncmap 0x0> <magic 0xa1822443> <pcomp> <accomp>]
rcvd [LCP ConfReq id=0x12 <asyncmap 0x0> <auth chap MD5> <magic 0xf726c96e> <pcomp> <accomp>]
No auth is possible
sent [LCP ConfRej id=0x12 <auth chap MD5>]
rcvd [LCP ConfAck id=0x1 <asyncmap 0x0> <magic 0xa1822443> <pcomp> <accomp>]
rcvd [LCP ConfReq id=0x13 <asyncmap 0x0> <magic 0xf726c96e> <pcomp> <accomp>]
sent [LCP ConfAck id=0x13 <asyncmap 0x0> <magic 0xf726c96e> <pcomp> <accomp>]
sent [LCP EchoReq id=0x0 magic=0xa1822443]
sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
rcvd [LCP DiscReq id=0x14 magic=0xf726c96e]
rcvd [LCP EchoRep id=0x0 magic=0xf726c96e a1 82 24 43]
rcvd [IPCP ConfReq id=0xc]
sent [IPCP ConfNak id=0xc <addr 0.0.0.0>]
rcvd [IPCP ConfNak id=0x1 <addr 10.177.14.221> <ms-dns1 89.19.64.44> <ms-dns2 89.19.64.172>]
sent [IPCP ConfReq id=0x2 <addr 10.177.14.221> <ms-dns1 89.19.64.44> <ms-dns2 89.19.64.172>]
rcvd [IPCP ConfReq id=0xd]
sent [IPCP ConfAck id=0xd]
rcvd [IPCP ConfAck id=0x2 <addr 10.177.14.221> <ms-dns1 89.19.64.44> <ms-dns2 89.19.64.172>]
Could not determine remote IP address: defaulting to 10.64.64.64
not replacing default route to wlan0 [172.20.10.1]
local  IP address 10.177.14.221
remote IP address 10.64.64.64
primary   DNS address 89.19.64.44
secondary DNS address 89.19.64.172
abhatikar@abhatikar-gateway:~$

**Comment by saeedjohar** [comment]
Running the following commands will solve the issue, 
**sudo route del default**
**sudo route add default ppp0**
