### ISSUE TITLE
Connect script failed

### ISSUE THREAD

**Issue by jamstooks** [sixfab/Sixfab_PPP_Installer#3]
Any suggestions on how I can debug the error below?

Device: Cellular IoT HAT
Carrier: [Ting](https://ting.com)
APN: `wholesale`
Tech: `NB-IoT`
Port: `ttyS0`

```
$ sudo pon
pppd options in effect:
debug		# (from /etc/ppp/peers/provider)
updetach		# (from /etc/ppp/peers/provider)
dump		# (from /etc/ppp/peers/provider)
noauth		# (from /etc/ppp/peers/provider)
remotename 3gppp		# (from /etc/ppp/peers/provider)
/dev/ttyS0		# (from /etc/ppp/peers/provider)
115200		# (from /etc/ppp/peers/provider)
lock		# (from /etc/ppp/peers/provider)
connect chat -s -v -f /etc/chatscripts/chat-connect -T wholesale		# (from /etc/ppp/peers/provider)
disconnect chat -s -v -f /etc/chatscripts/chat-disconnect		# (from /etc/ppp/peers/provider)
nocrtscts		# (from /etc/ppp/peers/provider)
modem		# (from /etc/ppp/peers/provider)
asyncmap 0		# (from /etc/ppp/options)
lcp-echo-failure 4		# (from /etc/ppp/options)
lcp-echo-interval 30		# (from /etc/ppp/options)
hide-password		# (from /etc/ppp/peers/provider)
novj		# (from /etc/ppp/peers/provider)
novjccomp		# (from /etc/ppp/peers/provider)
ipcp-accept-local		# (from /etc/ppp/peers/provider)
ipcp-accept-remote		# (from /etc/ppp/peers/provider)
ipparam 3gppp		# (from /etc/ppp/peers/provider)
noipdefault		# (from /etc/ppp/peers/provider)
ipcp-max-failure 30		# (from /etc/ppp/peers/provider)
defaultroute		# (from /etc/ppp/peers/provider)
usepeerdns		# (from /etc/ppp/peers/provider)
noccp		# (from /etc/ppp/peers/provider)
noipx		# (from /etc/ppp/options)
abort on (BUSY)
abort on (NO CARRIER)
abort on (NO DIALTONE)
abort on (ERROR)
abort on (NO ANSWER)
timeout set to 30 seconds
send (AT^M)
warning: write() on stdout returned 0
 -- write failed: Success
Failed
Script chat -s -v -f /etc/chatscripts/chat-connect -T wholesale finished (pid 9275), status = 0x1
Connect script failed
```

**Comment by saeedjohar** [comment]
Do you have Disabled Login shell to be accessible over serial and 
Enabled Serial port hardware? 

Please mention the status of LEDs of the Shield.

**Comment by jamstooks** [comment]
Thanks for the response. I updated my config with `raspi-conf`. Unfortunately, I'm still seeing the same error.

![raspi-config](https://user-images.githubusercontent.com/585436/57889833-b852d680-77ea-11e9-8c5c-8ec9f2e41e7a.png)

Here's a picture of the LEDs on the hat...

![leds](https://user-images.githubusercontent.com/585436/57889946-07007080-77eb-11e9-88c6-777da542cac6.jpg)

**Comment by jamstooks** [comment]
Thanks for the response. I updated my config with `raspi-conf`. Unfortunately, I'm still seeing the same error.

![raspi-config](https://user-images.githubusercontent.com/585436/57889833-b852d680-77ea-11e9-8c5c-8ec9f2e41e7a.png)

Here's a picture of the LEDs on the hat...

![leds](https://user-images.githubusercontent.com/585436/57940890-4ded7500-7882-11e9-9843-542b99565aaa.jpg)

**Comment by saeedjohar** [comment]
Hey, 
Seems your module is not powered up. 
Could you please use official RPi power supply (5V 2.5A)? 

Could you please manually power up the module pressing the POWER KEY? 
Once the module is powered up, you may see the STATUS LED turned ON and NETLIGHT LED BLINKING. 

If it doesn't solve, Please try sending AT commands vis ttyS0 using minicom.

**Comment by jamstooks** [comment]
Thanks for the suggestions. Ok, I've

- connected to the RPi power supply
- powered it up
- `NETLIGHT` flashes
- `STATUS` LED is brighter red

`AT` does not show any response in either `minicom` or `socat` using `sudo minicom /dev/ttyS0` and `sudo socat - /dev/ttyS0`.

Any other ideas?

Also, is it possible to have this power up when the Pi powers up, or will I have to hit the `PWRKEY` everytime?

![cellular-hat](https://user-images.githubusercontent.com/585436/58346199-22810200-7e0f-11e9-8ff2-edc0218e9adc.jpg)

**Comment by jamstooks** [comment]
**Update:** I was able to get this to work by connecting the USB jumper and using `/dev/ttyUSB3`.

I'd like to keep that USB port free, so if you have any advice on getting `/dev/ttyS0` working, I'd love to hear it.

Also, if you could tell me how to have this power up when the Pi boots, without having to use the `PWRKEY`, that would be awesome.

**Comment by robotra** [comment]
try ttyAMA0

**Comment by gunnarh79** [comment]
Hi i similar problem 

Can't get terminal parameters: Input/output error
Script chat -s -v -f /etc/chatscripts/chat-connect -T siminn finished (pid 648), status = 0x2
Connect script failed


I have good power supply.
I have power up the Raspberry Pi GSM/GPRS Shield

Any idea?

**Comment by NickNgHK** [comment]
Hi,
I got similar issue...
it only works with mPCIE with those 4 ttyUSBx
But when I tried to use the ttyS0, I have no way to get the ip address allocated.

Is it something related to the loaded Kernel modules? i.e. if attached the mPCIE -> USB serial driver loaded some modules that related to ip address module?

Any idea is appreciated!
 


=====
Sep 16 16:26:08 rpi4-broker chat[1065]: ^M
Sep 16 16:26:08 rpi4-broker sh[431]: Script chat -s -v -f /etc/chatscripts/chat-connect -T internet finished (pid 1064), status = 0x0
Sep 16 16:26:08 rpi4-broker sh[431]: Serial connection established.
Sep 16 16:26:08 rpi4-broker sh[431]: using channel 3
Sep 16 16:26:08 rpi4-broker sh[431]: Using interface ppp0
Sep 16 16:26:08 rpi4-broker sh[431]: Connect: ppp0 <--> /dev/ttyS0
Sep 16 16:26:08 rpi4-broker chat[1065]: CONNECT
Sep 16 16:26:08 rpi4-broker chat[1065]:  -- got it
Sep 16 16:26:08 rpi4-broker pppd[1063]: Script chat -s -v -f /etc/chatscripts/chat-connect -T internet finished (pid 1064), status = 0x0
Sep 16 16:26:08 rpi4-broker pppd[1063]: Serial connection established.
Sep 16 16:26:08 rpi4-broker pppd[1063]: using channel 3
Sep 16 16:26:08 rpi4-broker pppd[1063]: Using interface ppp0
Sep 16 16:26:08 rpi4-broker pppd[1063]: Connect: ppp0 <--> /dev/ttyS0
Sep 16 16:26:09 rpi4-broker pppd[1063]: sent [LCP ConfReq id=0x1 <asyncmap 0x0> <magic 0xae21f785> <pcomp> <accomp>]
Sep 16 16:26:09 rpi4-broker sh[431]: sent [LCP ConfReq id=0x1 <asyncmap 0x0> <magic 0xae21f785> <pcomp> <accomp>]
Sep 16 16:26:09 rpi4-broker pppd[1063]: rcvd [LCP ConfReq id=0x24 <asyncmap 0x0> <auth chap MD5> <magic 0xd5910979> <pcomp> <accomp>]
Sep 16 16:26:09 rpi4-broker sh[431]: rcvd [LCP ConfReq id=0x24 <asyncmap 0x0> <auth chap MD5> <magic 0xd5910979> <pcomp> <accomp>]
Sep 16 16:26:09 rpi4-broker sh[431]: No auth is possible
Sep 16 16:26:09 rpi4-broker sh[431]: sent [LCP ConfRej id=0x24 <auth chap MD5>]
Sep 16 16:26:09 rpi4-broker pppd[1063]: No auth is possible
Sep 16 16:26:09 rpi4-broker pppd[1063]: sent [LCP ConfRej id=0x24 <auth chap MD5>]
Sep 16 16:26:09 rpi4-broker sh[431]: rcvd [LCP ConfAck id=0x1 <asyncmap 0x0> <magic 0xae21f785> <pcomp> <accomp>]
Sep 16 16:26:09 rpi4-broker pppd[1063]: rcvd [LCP ConfAck id=0x1 <asyncmap 0x0> <magic 0xae21f785> <pcomp> <accomp>]
Sep 16 16:26:09 rpi4-broker pppd[1063]: rcvd [LCP ConfReq id=0x25 <asyncmap 0x0> <magic 0xd5910979> <pcomp> <accomp>]
Sep 16 16:26:09 rpi4-broker sh[431]: rcvd [LCP ConfReq id=0x25 <asyncmap 0x0> <magic 0xd5910979> <pcomp> <accomp>]
Sep 16 16:26:09 rpi4-broker sh[431]: sent [LCP ConfAck id=0x25 <asyncmap 0x0> <magic 0xd5910979> <pcomp> <accomp>]
Sep 16 16:26:09 rpi4-broker sh[431]: sent [LCP EchoReq id=0x0 magic=0xae21f785]
Sep 16 16:26:09 rpi4-broker sh[431]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:09 rpi4-broker pppd[1063]: sent [LCP ConfAck id=0x25 <asyncmap 0x0> <magic 0xd5910979> <pcomp> <accomp>]
Sep 16 16:26:09 rpi4-broker pppd[1063]: sent [LCP EchoReq id=0x0 magic=0xae21f785]
Sep 16 16:26:09 rpi4-broker pppd[1063]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:09 rpi4-broker pppd[1063]: rcvd [LCP DiscReq id=0x26 magic=0xd5910979]
Sep 16 16:26:09 rpi4-broker sh[431]: rcvd [LCP DiscReq id=0x26 magic=0xd5910979]
Sep 16 16:26:12 rpi4-broker pppd[1063]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:12 rpi4-broker sh[431]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:15 rpi4-broker pppd[1063]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:15 rpi4-broker sh[431]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:18 rpi4-broker pppd[1063]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:18 rpi4-broker sh[431]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:21 rpi4-broker pppd[1063]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:21 rpi4-broker sh[431]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:24 rpi4-broker pppd[1063]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:24 rpi4-broker sh[431]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:27 rpi4-broker pppd[1063]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:27 rpi4-broker sh[431]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:30 rpi4-broker pppd[1063]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 16 16:26:30 rpi4-broker sh[431]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]

=====
