### ISSUE TITLE
Wiringpi No Longer Available In Debian Bullseye

### ISSUE THREAD

**Issue by ip6li** [sixfab/Sixfab_PPP_Installer#31]
Wiringpi is no longer available In Debian Bullseye and should be replaced my an other GPIO solution supported by Bullseye.

**Comment by hiagofranco** [comment]
Same problem here. Maybe use this unofficial mirror: https://github.com/WiringPi/WiringPi . Original wiringpi is deprecated.

**Comment by ensarkarabudak** [comment]
This issue is fixed.
