### ISSUE TITLE
sudo route add default ppp0

### ISSUE THREAD

**Issue by saoron** [sixfab/Sixfab_PPP_Installer#4]
Hi Guys,
Any chance to automate this command?
> sudo route del default
sudo route add default ppp0

Thanks,

**Comment by selengalp** [comment]
Hi, 
You can add these lines on reconnect.service. 

Please follow commands below:

`sudo nano /usr/src/reconnect.sh`

Add `sudo ip route add default dev ppp0` as below. 
```
...
echo "Connection down, reconnecting..."
sudo pon
sudo ip route add default dev ppp0
... 
```

Save and exit.

```
sudo systemctl daemon-reload 
sudo reboot
```

**Comment by saoron** [comment]
Works! Thank you
