### ISSUE TITLE
ppp_connection_manager.service - will only run once instead of intended 4 times

### ISSUE THREAD

**Issue by r-colvin** [sixfab/Sixfab_PPP_Installer#40]
it is intended that ppp_connection_manager.service will run up to 4 times if necessary, however due to two issues it will always only run once

1. exit code of configure_modem.sh should be captured and checked (MODEM_CONFIG is never set)
2. i is never incremented

pull request to correct issue: https://github.com/sixfab/Sixfab_PPP_Installer/pull/39

**Comment by selengalp** [comment]
I've answered all questions in PR review. Thank you for your contribution.

**Comment by r-colvin** [comment]
great, will close the issue
