### ISSUE TITLE
install.sh

### ISSUE THREAD

**Issue by OmniLumous** [sixfab/Sixfab_PPP_Installer#5]
I have followed the instructions and cloned the directory, though nothing occurres while running the install.sh 

I have also opened the cloned directory folder and exicuted the install.sh there though again nothing occurres.

And finally I downloaded the .zip, moved the files to my pi & tried exicuting the install that way, but with the same result. 

I'm guessing this is the latest for the PPP? Your product page after purchase still links to an old set of instructions; which have you try and install from no longer existing GitHub directories. Which makes setting up the 3g/4g lte had quite annoying...

**Comment by saeedjohar** [comment]
Please share the log you are getting after executing install.sh

Thank you for informing about the links
